AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: The best API ever!

Globals:
  Api:
    Cors: "'*'"

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist/package.zip
      Handler: DUMMY
      Runtime: provided
      MemorySize: 256
      Timeout: 15
      Environment:
        Variables:
          ASPNETCORE_ENVIRONMENT: Production
      Events:
        Web:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        WebRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
